module.exports = [
  {
    id: 'gxp1400',
    name: 'GXP1400',
    type: 'phone',
    template: 'grandstream/default_phone.xml',
    accounts: 2,
  },
  {
    id: 'gxp1610',
    name: 'GXP1610',
    type: 'phone',
    template: 'grandstream/default_phone.xml',
    accounts: 1,
  },
  {
    id: 'gxp1620',
    name: 'GXP1620',
    type: 'phone',
    template: 'grandstream/default_phone.xml',
    accounts: 2,
  },
  {
    id: 'dp715',
    name: 'DP715',
    type: 'gateway',
    template: 'grandstream/default_gateway.xml',
    accounts: 5,
    profiles: 2,
  },
  {
    id: 'ht812',
    name: 'HT812',
    type: 'gateway',
    template: 'grandstream/default_gateway.xml',
    accounts: 2,
    profiles: 2,
  },
  {
    id: 'ht814',
    name: 'HT814',
    type: 'gateway',
    template: 'grandstream/default_gateway.xml',
    accounts: 4,
    profiles: 2,
  },
  {
    id: 'gxw4008',
    name: 'GXW4008',
    type: 'gateway',
    template: 'grandstream/default_gateway.xml',
    accounts: 8,
    profiles: 2,
  },
];
